discourse_subrite:
  subrite_enabled:
    default: false
  subrite_discovery_document:
    default: ""
  subrite_client_id:
    default: ""
  subrite_client_secret:
    default: ""
    secret: true
  subrite_rp_initiated_logout:
    default: false
  subrite_rp_initiated_logout_redirect:
    default: ""
  subrite_allow_association_change:
    default: false
  subrite_overrides_email:
    default: true
  subrite_authorize_scope:
    default: "openid email profile offline_access"
  subrite_verbose_logging:
    default: false
  subrite_token_scope:
    default: ""
  subrite_error_redirects:
    default: ""
    type: list
    list_type: secret
  subrite_authorize_parameters:
    default: ""
    type: list
    list_type: compact
  subrite_claims:
    default: ""
    textarea: true
  subrite_match_by_email:
    default: true
  subrite_use_pkce:
    default: false
